# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Valeur')),
            ],
        ),
        migrations.CreateModel(
            name='BonusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(blank=True, max_length=255, verbose_name='Nom (FR)')),
                ('name_en', models.CharField(max_length=255, unique=True, verbose_name='Nom (EN)')),
                ('stacks', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=255, verbose_name='Nom (FR)')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(blank=True, max_length=255, verbose_name='Nom (FR)')),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='stats',
            field=models.ManyToManyField(through='buffs.Bonus', to='buffs.Stat'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buffs.Source'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buffs.Stat', verbose_name='Attribut modifié'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buffs.BonusType', verbose_name='Type de bonus'),
        ),
    ]
