# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# buffs.migrations.0002_auto_20160308_1842

def populate_bonus_types(apps, schema_editor):
    BonusType = apps.get_model("buffs", "BonusType")
    BonusType.objects.bulk_create([
        BonusType(name_fr=fr, name_en=en, stacks=stacks)
        for en, fr, stacks in [
            ('Alchemical', 'Alchimique', False),
            ('Armor', 'Armure', False),
            ('Circumstance', 'Circompstance', True),
            ('Competence', 'Aptitude', False),
            ('Deflection', '???', False),
            ('Dodge', '???', True),
            ('Enhancement', '???', False),
            ('Insight', '???', False),
            ('Luck', 'Chance', False),
            ('Morale', 'Moral', False),
            ('Natural Armor', 'Armure Naturelle', False),
            ('Profane', "???", False),
            ('Resistance', 'Résistance', False),
            ('Sacred', 'Sacré', False),
            ('Size', 'Taille', True),
            ('Untyped', 'Non-typé', True),
        ]
    ])

class Migration(migrations.Migration):

    replaces = [('buffs', '0001_initial'), ('buffs', '0002_auto_20160308_1842'), ('buffs', '0003_auto_20160308_1853'), ('buffs', '0004_auto_20160308_1853'), ('buffs', '0005_auto_20160308_1853'), ('buffs', '0006_auto_20160308_1940'), ('buffs', '0007_auto_20160308_2206'), ('buffs', '0008_auto_20160308_2331')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Valeur')),
            ],
        ),
        migrations.CreateModel(
            name='BonusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(blank=True, max_length=255, verbose_name='Nom (FR)')),
                ('name_en', models.CharField(max_length=255, unique=True, verbose_name='Nom (EN)')),
                ('stacks', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=255, verbose_name='Nom (FR)')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(blank=True, max_length=255, verbose_name='Nom (FR)')),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='stats',
            field=models.ManyToManyField(through='buffs.Bonus', to='buffs.Stat'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buffs.Source'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buffs.Stat', verbose_name='Attribut modifié'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buffs.BonusType', verbose_name='Type de bonus'),
        ),
        migrations.CreateModel(
            name='ConstrainedStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(blank=True, max_length=255, verbose_name='Nom (FR)')),
            ],
        ),
        migrations.AlterField(
            model_name='stat',
            name='name_fr',
            field=models.CharField(max_length=255, verbose_name='Nom (FR)'),
        ),
        migrations.AddField(
            model_name='constrainedstat',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buffs.Stat'),
        ),
        migrations.AlterUniqueTogether(
            name='constrainedstat',
            unique_together=set([('stat', 'name_fr')]),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buffs.ConstrainedStat', verbose_name='Attribut modifié'),
        ),
        migrations.AlterField(
            model_name='source',
            name='stats',
            field=models.ManyToManyField(through='buffs.Bonus', to='buffs.ConstrainedStat'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('undead', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buffs.Character', verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='source',
            name='level_dependent',
            field=models.BooleanField(default=False, verbose_name='Dépend du niveau'),
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('characters', models.ManyToManyField(to='buffs.Character')),
                ('effects', models.ManyToManyField(through='buffs.Effect', to='buffs.Source')),
            ],
        ),
        migrations.AddField(
            model_name='effect',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buffs.Group'),
        ),
        migrations.AddField(
            model_name='effect',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buffs.Source'),
        ),
        migrations.RunPython(populate_bonus_types),
    ]
