# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 18:42
from __future__ import unicode_literals

from django.db import migrations

def populate_bonus_types(apps, schema_editor):
    BonusType = apps.get_model("buffs", "BonusType")
    BonusType.objects.bulk_create([
        BonusType(name_fr=fr, name_en=en, stacks=stacks)
        for en, fr, stacks in [
            ('Alchemical', 'Alchimique', False),
            ('Armor', 'Armure', False),
            ('Circumstance', 'Circompstance', True),
            ('Competence', 'Aptitude', False),
            ('Deflection', '???', False),
            ('Dodge', '???', True),
            ('Enhancement', '???', False),
            ('Insight', '???', False),
            ('Luck', 'Chance', False),
            ('Morale', 'Moral', False),
            ('Natural Armor', 'Armure Naturelle', False),
            ('Profane', "???", False),
            ('Resistance', 'Résistance', False),
            ('Sacred', 'Sacré', False),
            ('Size', 'Taille', True),
            ('Untyped', 'Non-typé', True),
        ]
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('buffs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_bonus_types),
    ]
