# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffs', '0002_auto_20160308_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='stats',
            field=models.ManyToManyField(through='buffs.Bonus', to='buffs.Stat'),
        ),
    ]
