# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 09:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buffs', '0003_source_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='sources',
            new_name='source',
        ),
        migrations.AddField(
            model_name='character',
            name='players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
