# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buffs', '0004_auto_20160308_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buffs.ConstrainedStat', verbose_name='Attribut modifié'),
        ),
        migrations.AlterField(
            model_name='source',
            name='stats',
            field=models.ManyToManyField(through='buffs.Bonus', to='buffs.ConstrainedStat'),
        ),
    ]
