# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buffs', '0005_auto_20160308_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sources', models.ManyToManyField(through='buffs.Buff', to='buffs.Source')),
            ],
        ),
        migrations.AddField(
            model_name='buff',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buffs.Character'),
        ),
        migrations.AddField(
            model_name='buff',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buffs.Source'),
        ),
    ]
