# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffs', '0005_auto_20160309_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='buff',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
