# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buffs', '0006_auto_20160308_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='undead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='source',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buffs.Character', verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='source',
            name='level_dependent',
            field=models.BooleanField(default=False, verbose_name='Dépend du niveau'),
        ),
    ]
