# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buffs', '0006_buff_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bonus',
            unique_together=set([('source', 'stat', 'constraint', 'typ')]),
        ),
    ]
