# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buffs', '0007_auto_20160309_1101'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bonus',
            unique_together=set([('source', 'typ', 'stat', 'constraint')]),
        ),
    ]
