# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buffs', '0008_auto_20160309_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='typ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buffs.BonusType', verbose_name='Type de bonus'),
        ),
    ]
