# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buffs', '0011_buff_characters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='group',
            name='source',
        ),
        migrations.AlterUniqueTogether(
            name='buff',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='buff',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
