# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffs', '0012_auto_20160309_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='source',
            name='stats',
            field=models.ManyToManyField(through='buffs.Bonus', to='buffs.Stat'),
        ),
    ]
